# Generated by Django 5.2.4 on 2025-08-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('acerca_de_mi', models.TextField(blank=True, max_length=500, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('mostrar_cumpleanos', models.BooleanField(default=True)),
                ('mostrar_edad', models.BooleanField(default=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace de Twitter')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace de Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace de LinkedIn')),
                ('configuracion_privacidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('seguidores', 'Seguidores')], default='publico', max_length=20, verbose_name='Configuración de Privacidad')),
                ('recibir_emails_recetas_nuevas', models.BooleanField(default=True, verbose_name='Recibir emails de recetas nuevas')),
                ('recibir_emails_mensajes_privados', models.BooleanField(default=True, verbose_name='Recibir emails de mensajes privados')),
                ('permitir_mensajes_privados', models.BooleanField(default=True, verbose_name='Permitir mensajes privados')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('is_leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos_usuarios', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje Privado de Usuarios',
                'verbose_name_plural': 'Mensajes Privados de Usuarios',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Favorito',
                'verbose_name_plural': 'Categorías de Favoritos',
                'unique_together': {('user', 'nombre')},
            },
        ),
    ]
